name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: fastapi-practice

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::705166993722:role/GithubActionsRunner
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Docker image ready: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Deploy to EC2 via SSM
      run: |
        aws ssm send-command \
        --targets "Key=InstanceIds,Values=i-01fea80a9937b9520" \
        --document-name "AWS-RunShellScript" \
        --comment "Deploy FastAPI Docker container" \
        --parameters '{
            "commands": [
            "aws ecr get-login-password --region '${{ env.AWS_REGION }}' | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}",
            "docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}-${{ github.sha }}",
            "docker stop fastapi-container || true",
            "docker rm fastapi-container || true",
            "docker run -d --name fastapi-container -p 8000:8000 ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}-${{ github.sha }}"
            ]
        }' \
        --region ${{ env.AWS_REGION }}
        